In [24]:
import torch
import random
import numpy as np
import torch.nn as nn

In [14]:
class BIM(nn.Module):
    def __init__(self, l_dim, r_dim):
        super(BIM, self).__init__()
        self.W = nn.Bilinear(l_dim*2, r_dim, 1, bias=False)
        
    def forward(self, e1, e2, q):
        """
        e1: tensor of size (*, l_dim)
        e2: tensor of size (*, r_dim)

        return: tensor of size (*, 1)
        """
        e = torch.cat((e1, e2), -1)
        return self.W(e, q)

tensor([0, 3, 4, 3, 1, 2, 2, 3, 3, 2])

In [19]:


mask = torch.arange(5).expand(10,5)<torch.randint(5,(10,)).unsqueeze(1)

In [22]:
torch.randint(5,(10,)).unsqueeze(1)

tensor([[4],
        [4],
        [0],
        [4],
        [0],
        [2],
        [0],
        [3],
        [4],
        [0]])

In [23]:
torch.arange(5).expand(10,5)

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

In [56]:
bil = torch.nn.Bilinear(5,5,1)

In [69]:
A0 = torch.rand(8,5)
B = torch.rand(8,4,5)

In [82]:
torch.functional.softmax

tensor([[[0.2789, 0.1589, 0.0803, 0.0104, 0.4484],
         [0.2789, 0.1589, 0.0803, 0.0104, 0.4484],
         [0.2789, 0.1589, 0.0803, 0.0104, 0.4484],
         [0.2789, 0.1589, 0.0803, 0.0104, 0.4484]],

        [[0.8068, 0.8107, 0.1455, 0.7597, 0.2093],
         [0.8068, 0.8107, 0.1455, 0.7597, 0.2093],
         [0.8068, 0.8107, 0.1455, 0.7597, 0.2093],
         [0.8068, 0.8107, 0.1455, 0.7597, 0.2093]],

        [[0.9359, 0.2825, 0.0064, 0.9988, 0.5549],
         [0.9359, 0.2825, 0.0064, 0.9988, 0.5549],
         [0.9359, 0.2825, 0.0064, 0.9988, 0.5549],
         [0.9359, 0.2825, 0.0064, 0.9988, 0.5549]],

        [[0.0382, 0.1902, 0.6561, 0.8713, 0.1071],
         [0.0382, 0.1902, 0.6561, 0.8713, 0.1071],
         [0.0382, 0.1902, 0.6561, 0.8713, 0.1071],
         [0.0382, 0.1902, 0.6561, 0.8713, 0.1071]],

        [[0.6562, 0.6876, 0.5426, 0.8241, 0.1390],
         [0.6562, 0.6876, 0.5426, 0.8241, 0.1390],
         [0.6562, 0.6876, 0.5426, 0.8241, 0.1390],
         [0.6562, 0.687

In [66]:
bil(A,B)

tensor([[[-0.1522],
         [ 0.0375],
         [ 0.1015],
         [ 0.1446]],

        [[-0.2623],
         [ 0.7441],
         [ 0.2098],
         [ 0.8267]],

        [[ 0.1457],
         [-0.1468],
         [-0.1154],
         [ 0.4992]],

        [[ 0.1788],
         [-0.3987],
         [ 0.6514],
         [-0.3051]],

        [[-0.0424],
         [ 0.2975],
         [ 0.5569],
         [ 0.0133]],

        [[-0.0905],
         [-0.0808],
         [ 0.3464],
         [ 0.0910]],

        [[ 0.0222],
         [ 0.3377],
         [ 0.1375],
         [-0.0044]],

        [[ 0.0626],
         [ 0.4519],
         [-0.0115],
         [ 0.3840]]], grad_fn=<AddBackward0>)